In [ ]:
import tensorflow as tf
print(tf.__version__)

2.6.0


In [ ]:
tensor = tf.constant([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9],
                      [10, 11, 12]])
tensor

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
tensor.shape

TensorShape([4, 3])

In [ ]:
tf.random.shuffle(tensor, seed=50)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 4,  5,  6],
       [10, 11, 12],
       [ 7,  8,  9],
       [ 1,  2,  3]], dtype=int32)>

In [ ]:
rtensor = tf.random.Generator.from_seed(100)
rtensor = rtensor.uniform(shape=[3,4], dtype=tf.int32, minval=3, maxval=100)
rtensor

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[65, 92, 66, 91],
       [ 8, 32, 48, 20],
       [84, 35, 67, 16]], dtype=int32)>

In [ ]:
tf.expand_dims(rtensor, -1)

<tf.Tensor: shape=(3, 4, 1), dtype=int32, numpy=
array([[[65],
        [92],
        [66],
        [91]],

       [[ 8],
        [32],
        [48],
        [20]],

       [[84],
        [35],
        [67],
        [16]]], dtype=int32)>

In [ ]:
rtensor[..., tf.newaxis]

<tf.Tensor: shape=(3, 4, 1), dtype=int32, numpy=
array([[[65],
        [92],
        [66],
        [91]],

       [[ 8],
        [32],
        [48],
        [20]],

       [[84],
        [35],
        [67],
        [16]]], dtype=int32)>

In [ ]:
rtensor

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[65, 92, 66, 91],
       [ 8, 32, 48, 20],
       [84, 35, 67, 16]], dtype=int32)>

In [ ]:
tf.dtypes.saturate_cast(rtensor, tf.float32)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[65., 92., 66., 91.],
       [ 8., 32., 48., 20.],
       [84., 35., 67., 16.]], dtype=float32)>

In [ ]:
tf.cast(rtensor, dtype=tf.float32)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[65., 92., 66., 91.],
       [ 8., 32., 48., 20.],
       [84., 35., 67., 16.]], dtype=float32)>

In [ ]:
tf.sqrt(tf.cast(rtensor, dtype=tf.float32))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[8.062258 , 9.591663 , 8.124039 , 9.539392 ],
       [2.8284273, 5.6568546, 6.9282036, 4.4721365],
       [9.165152 , 5.91608  , 8.185353 , 4.       ]], dtype=float32)>

In [ ]:
tf.math.square(rtensor)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[4225, 8464, 4356, 8281],
       [  64, 1024, 2304,  400],
       [7056, 1225, 4489,  256]], dtype=int32)>

In [ ]:
rtensor2 = tf.random.Generator.from_seed(42)
rtensor2 = rtensor2.uniform(shape=(3,2), dtype=tf.int32, maxval=100, minval=1)

tensor2=tf.constant([[1, 2, 1],
                     [2, 1, 2]])
tensor2, rtensor2

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 1],
        [2, 1, 2]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[70, 31],
        [43, 31],
        [94, 67]], dtype=int32)>)

In [ ]:
tensor2 @ rtensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[250, 160],
       [371, 227]], dtype=int32)>

In [ ]:
tf.matmul(tensor2, rtensor2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[250, 160],
       [371, 227]], dtype=int32)>

In [ ]:
rtensor2 @ tensor2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[132, 171, 132],
       [105, 117, 105],
       [228, 255, 228]], dtype=int32)>

In [ ]:
tf.matmul(rtensor2, tensor2)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[132, 171, 132],
       [105, 117, 105],
       [228, 255, 228]], dtype=int32)>

In [ ]:
tensor2, tf.reshape(tensor2, shape=(3,2)), tf.transpose(tensor2)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 1],
        [2, 1, 2]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [1, 2],
        [1, 2]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [2, 1],
        [1, 2]], dtype=int32)>)

In [ ]:
c = tf.constant([-40, -10, 40 , 0, 15, 22, 30, 38, 50, 80], dtype=tf.float32)
f = tf.constant([-40, 14, 104, 32, 59, 72, 86, 100, 122, 176], dtype=tf.float32)

c,f

(<tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([-40., -10.,  40.,   0.,  15.,  22.,  30.,  38.,  50.,  80.],
       dtype=float32)>, <tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([-40.,  14., 104.,  32.,  59.,  72.,  86., 100., 122., 176.],
       dtype=float32)>)

In [ ]:
model = tf.keras.Sequential([
  tf.keras.layers.Dense(units=1, input_shape=[1])
])

model.compile(loss='mean_squared_error', optimizer=tf.keras.optimizers.Adam(0.1))

model.fit(c,f, epochs=1000, verbose=False)
print("finished")


finished


In [ ]:
print(model.predict([12]))

[[53.298954]]


In [ ]:
list= [0,12,4,2]
tf.one_hot(list, depth=13, on_value=2, off_value=0)

<tf.Tensor: shape=(4, 13), dtype=int32, numpy=
array([[2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2],
       [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

In [ ]:
tf.config.list_physical_devices()
!nvidia-smi

Thu Sep 23 18:01:03 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.63.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   73C    P0    73W / 149W |    123MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------